name: Day12 CI Pipeline

on:
 push:
  branches: "main"

jobs:
  test-and-build:
    runs-on: ubuntu-latest

steps:
  -name: checkout code
   run: actions/checkout@v3

  -name: install python
   run: actions/setup-python@v4
    with: 
      python-version: " 3.11"

  -name: install requirements file
   run: pip install requirements.txt

  -name: test the code
   run: python -c "import app.main"

  -name: build docker image
   run: docker build -t "fastapi" .

